-- Copy and paste this into the Supabase SQL Editor to set up your database

-- 1. Create News Table
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    content TEXT,
    published_at DATE,
    category TEXT DEFAULT 'お知らせ',
    is_published BOOLEAN DEFAULT TRUE
);

-- 2. Enable Security for News
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Access" 
ON public.news FOR SELECT 
USING (true);

CREATE POLICY "Admin Access" 
ON public.news FOR ALL 
USING (auth.role() = 'authenticated');

-- 3. Create Works Table
CREATE TABLE IF NOT EXISTS public.works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    location TEXT,
    description TEXT,
    image_url TEXT,
    completion_date DATE
);

-- 4. Enable Security for Works
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Access" 
ON public.works FOR SELECT 
USING (true);

CREATE POLICY "Admin Access" 
ON public.works FOR ALL 
USING (auth.role() = 'authenticated');

-- 5. Create Storage Bucket for Images
insert into storage.buckets (id, name, public) 
values ('images', 'images', true) 
on conflict (id) do nothing;

-- 6. Storage Security Policies
create policy "Public Access" 
on storage.objects for select 
using ( bucket_id = 'images' );

create policy "Admin Upload" 
on storage.objects for insert 
using ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- 7. Seed Initial Data (Optional)
INSERT INTO public.news (title, published_at, category, content)
VALUES 
    ('ウェブサイトをリニューアルしました', CURRENT_DATE, 'お知らせ', 'M''S Worksの公式ウェブサイトをリニューアルしました。今後ともよろしくお願いいたします。');
